import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import ReactFullpage from '@fullpage/react-fullpage'
import Hero from '@/components/Hero'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <ReactFullpage
        licenseKey={'YOUR_KEY_HERE'}
        scrollingSpeed={1000}
        animateAnchor={true}
        anchors={['', 'sabrage', 'vinhos']}
        responsiveHeight='650'

        render={({ state, fullpageApi }) => {
          return (
            <ReactFullpage.Wrapper>
              <div className="section">
                <Hero />
              </div>
              <div className="section">
                two
              </div>
              <div className="section">
                three
              </div>
            </ReactFullpage.Wrapper>
          )
        }}
      />
    </>
  )
}
